# This is not executable on purpose and is used by irb_conformance

require 'google/protobuf'
require 'conformance/conformance_pb'
require 'conformance/test_protos/test_messages_edition2023_pb'
# require 'google/protobuf'
require 'google/protobuf/test_messages_proto3_pb'
require 'google/protobuf/test_messages_proto2_pb'
require 'test_messages_proto2_editions_pb'
require 'test_messages_proto3_editions_pb'
require 'base64'
require 'pry'

# Ruby classes generated with protoboeuf don't populate Google's descriptor pool.
# We can just look them up by class name in memory and return them in a wrapper.
FoundMsgClass = Struct.new(:msgclass)
Google::Protobuf::DescriptorPool.generated_pool.singleton_class.prepend(Module.new do
  def lookup(type)
    super || begin
      klass = type.split(".").map { |x| x.match?(/^[A-Z]/) ? x : x.split('_').map(&:capitalize).join("") }.join("::")
      # STDERR.puts "USING #{klass}"
      FoundMsgClass.new(Object.const_get(klass))
    end
  end
end)

serialized_request_json = {"protobufPayload":"YQAAAAAAAAAA\n","requestedOutputFormat":"2","messageType":"cHJvdG9idWZfdGVzdF9tZXNzYWdlcy5wcm90bzMuVGVzdEFsbFR5cGVzUHJv\ndG8z\n","testCategory":"1","jspbEncodingOptions":{},"printUnknownFields":false }
# response = {"jsonPayload":"eyJvcHRpb25hbEludDMyIjoiMCIsIm9wdGlvbmFsSW50NjQiOiIwIiwib3B0\naW9uYWxVaW50MzIiOiIwIiwib3B0aW9uYWxVaW50NjQiOiIwIiwib3B0aW9u\nYWxTaW50MzIiOiIwIiwib3B0aW9uYWxTaW50NjQiOiIwIiwib3B0aW9uYWxG\naXhlZDMyIjoiMCIsIm9wdGlvbmFsRml4ZWQ2NCI6IjAiLCJvcHRpb25hbFNm\naXhlZDMyIjoiMCIsIm9wdGlvbmFsU2ZpeGVkNjQiOiIwIiwib3B0aW9uYWxG\nbG9hdCI6IjAuMCIsIm9wdGlvbmFsRG91YmxlIjoiMC4wIiwib3B0aW9uYWxC\nb29sIjpmYWxzZSwib3B0aW9uYWxTdHJpbmciOiIiLCJvcHRpb25hbEJ5dGVz\nIjoiIiwib3B0aW9uYWxOZXN0ZWRNZXNzYWdlIjp7fSwib3B0aW9uYWxGb3Jl\naWduTWVzc2FnZSI6e30sIm9wdGlvbmFsTmVzdGVkRW51bSI6IjAiLCJvcHRp\nb25hbEZvcmVpZ25FbnVtIjoiMCIsIm9wdGlvbmFsQWxpYXNlZEVudW0iOiIw\nIiwib3B0aW9uYWxTdHJpbmdQaWVjZSI6IiIsIm9wdGlvbmFsQ29yZCI6IiIs\nInJlY3Vyc2l2ZU1lc3NhZ2UiOnt9LCJyZXBlYXRlZEludDMyIjpbXSwicmVw\nZWF0ZWRJbnQ2NCI6W10sInJlcGVhdGVkVWludDMyIjpbXSwicmVwZWF0ZWRV\naW50NjQiOltdLCJyZXBlYXRlZFNpbnQzMiI6W10sInJlcGVhdGVkU2ludDY0\nIjpbXSwicmVwZWF0ZWRGaXhlZDMyIjpbXSwicmVwZWF0ZWRGaXhlZDY0Ijpb\nXSwicmVwZWF0ZWRTZml4ZWQzMiI6W10sInJlcGVhdGVkU2ZpeGVkNjQiOltd\nLCJyZXBlYXRlZEZsb2F0IjpbXSwicmVwZWF0ZWREb3VibGUiOltdLCJyZXBl\nYXRlZEJvb2wiOltdLCJyZXBlYXRlZFN0cmluZyI6W10sInJlcGVhdGVkQnl0\nZXMiOltdLCJyZXBlYXRlZE5lc3RlZE1lc3NhZ2UiOltdLCJyZXBlYXRlZEZv\ncmVpZ25NZXNzYWdlIjpbXSwicmVwZWF0ZWROZXN0ZWRFbnVtIjpbXSwicmVw\nZWF0ZWRGb3JlaWduRW51bSI6W10sInJlcGVhdGVkU3RyaW5nUGllY2UiOltd\nLCJyZXBlYXRlZENvcmQiOltdLCJwYWNrZWRJbnQzMiI6W10sInBhY2tlZElu\ndDY0IjpbXSwicGFja2VkVWludDMyIjpbXSwicGFja2VkVWludDY0IjpbXSwi\ncGFja2VkU2ludDMyIjpbXSwicGFja2VkU2ludDY0IjpbXSwicGFja2VkRml4\nZWQzMiI6W10sInBhY2tlZEZpeGVkNjQiOltdLCJwYWNrZWRTZml4ZWQzMiI6\nW10sInBhY2tlZFNmaXhlZDY0IjpbXSwicGFja2VkRmxvYXQiOltdLCJwYWNr\nZWREb3VibGUiOltdLCJwYWNrZWRCb29sIjpbXSwicGFja2VkTmVzdGVkRW51\nbSI6W10sInVucGFja2VkSW50MzIiOltdLCJ1bnBhY2tlZEludDY0IjpbXSwi\ndW5wYWNrZWRVaW50MzIiOltdLCJ1bnBhY2tlZFVpbnQ2NCI6W10sInVucGFj\na2VkU2ludDMyIjpbXSwidW5wYWNrZWRTaW50NjQiOltdLCJ1bnBhY2tlZEZp\neGVkMzIiOltdLCJ1bnBhY2tlZEZpeGVkNjQiOltdLCJ1bnBhY2tlZFNmaXhl\nZDMyIjpbXSwidW5wYWNrZWRTZml4ZWQ2NCI6W10sInVucGFja2VkRmxvYXQi\nOltdLCJ1bnBhY2tlZERvdWJsZSI6W10sInVucGFja2VkQm9vbCI6W10sInVu\ncGFja2VkTmVzdGVkRW51bSI6W10sIm1hcEludDMySW50MzIiOnt9LCJtYXBJ\nbnQ2NEludDY0Ijp7fSwibWFwVWludDMyVWludDMyIjp7fSwibWFwVWludDY0\nVWludDY0Ijp7fSwibWFwU2ludDMyU2ludDMyIjp7fSwibWFwU2ludDY0U2lu\ndDY0Ijp7fSwibWFwRml4ZWQzMkZpeGVkMzIiOnt9LCJtYXBGaXhlZDY0Rml4\nZWQ2NCI6e30sIm1hcFNmaXhlZDMyU2ZpeGVkMzIiOnt9LCJtYXBTZml4ZWQ2\nNFNmaXhlZDY0Ijp7fSwibWFwSW50MzJGbG9hdCI6e30sIm1hcEludDMyRG91\nYmxlIjp7fSwibWFwQm9vbEJvb2wiOnt9LCJtYXBTdHJpbmdTdHJpbmciOnt9\nLCJtYXBTdHJpbmdCeXRlcyI6e30sIm1hcFN0cmluZ05lc3RlZE1lc3NhZ2Ui\nOnt9LCJtYXBTdHJpbmdGb3JlaWduTWVzc2FnZSI6e30sIm1hcFN0cmluZ05l\nc3RlZEVudW0iOnt9LCJtYXBTdHJpbmdGb3JlaWduRW51bSI6e30sIm9wdGlv\nbmFsQm9vbFdyYXBwZXIiOnt9LCJvcHRpb25hbEludDMyV3JhcHBlciI6e30s\nIm9wdGlvbmFsSW50NjRXcmFwcGVyIjp7fSwib3B0aW9uYWxVaW50MzJXcmFw\ncGVyIjp7fSwib3B0aW9uYWxVaW50NjRXcmFwcGVyIjp7fSwib3B0aW9uYWxG\nbG9hdFdyYXBwZXIiOnt9LCJvcHRpb25hbERvdWJsZVdyYXBwZXIiOnt9LCJv\ncHRpb25hbFN0cmluZ1dyYXBwZXIiOnt9LCJvcHRpb25hbEJ5dGVzV3JhcHBl\nciI6e30sInJlcGVhdGVkQm9vbFdyYXBwZXIiOltdLCJyZXBlYXRlZEludDMy\nV3JhcHBlciI6W10sInJlcGVhdGVkSW50NjRXcmFwcGVyIjpbXSwicmVwZWF0\nZWRVaW50MzJXcmFwcGVyIjpbXSwicmVwZWF0ZWRVaW50NjRXcmFwcGVyIjpb\nXSwicmVwZWF0ZWRGbG9hdFdyYXBwZXIiOltdLCJyZXBlYXRlZERvdWJsZVdy\nYXBwZXIiOltdLCJyZXBlYXRlZFN0cmluZ1dyYXBwZXIiOltdLCJyZXBlYXRl\nZEJ5dGVzV3JhcHBlciI6W10sIm9wdGlvbmFsRHVyYXRpb24iOnt9LCJvcHRp\nb25hbFRpbWVzdGFtcCI6e30sIm9wdGlvbmFsRmllbGRNYXNrIjp7fSwib3B0\naW9uYWxTdHJ1Y3QiOnt9LCJvcHRpb25hbEFueSI6e30sIm9wdGlvbmFsVmFs\ndWUiOnt9LCJvcHRpb25hbE51bGxWYWx1ZSI6IjAiLCJyZXBlYXRlZER1cmF0\naW9uIjpbXSwicmVwZWF0ZWRUaW1lc3RhbXAiOltdLCJyZXBlYXRlZEZpZWxk\nbWFzayI6W10sInJlcGVhdGVkU3RydWN0IjpbXSwicmVwZWF0ZWRBbnkiOltd\nLCJyZXBlYXRlZFZhbHVlIjpbXSwicmVwZWF0ZWRMaXN0VmFsdWUiOltdLCJm\naWVsZG5hbWUxIjoiMCIsImZpZWxkTmFtZTIiOiIwIiwiRmllbGROYW1lMyI6\nIjAiLCJmaWVsZF9OYW1lNF8iOiIwIiwiZmllbGQwbmFtZTUiOiIwIiwiZmll\nbGRfME5hbWU2IjoiMCIsImZpZWxkTmFtZTciOiIwIiwiRmllbGROYW1lOCI6\nIjAiLCJmaWVsZF9OYW1lOSI6IjAiLCJGaWVsZF9OYW1lMTAiOiIwIiwiRklF\nTERfTkFNRTExIjoiMCIsIkZJRUxETmFtZTEyIjoiMCIsIl9GaWVsZE5hbWUx\nMyI6IjAiLCJfX0ZpZWxkTmFtZTE0IjoiMCIsImZpZWxkX05hbWUxNSI6IjAi\nLCJmaWVsZF9fTmFtZTE2IjoiMCIsImZpZWxkTmFtZTE3X18iOiIwIiwiRmll\nbGROYW1lMThfXyI6IjAifQ==\n" }

request_payload_protobuf = Base64.decode64(serialized_request_json[:protobufPayload])
message_type = Base64.decode64(serialized_request_json[:messageType])

descriptor = Google::Protobuf::DescriptorPool.generated_pool.lookup(message_type)

test_message = descriptor.msgclass.decode(request_payload_protobuf)

binding.pry
